### ISSUE TITLE
If the organisation belongs to user, Add an Edit Org Button to the organization page

### ISSUE THREAD

**Issue by Sarfraz-droid** [scorelab/Codelabz#474] opened 2022-10-13 15:19 UTC
![image](https://user-images.githubusercontent.com/73013838/195637467-3cb34ca3-8679-4466-97ba-eee22c93c5e0.png)

this will reditrect to Org's Settings.

![image](https://user-images.githubusercontent.com/73013838/195637658-08f6c491-b4b1-46fe-a0a5-6f00178f43b1.png)

**Comment by ayush3160** [comment] 2022-10-15 12:40
Hi @Sarfraz-droid  can I work on this issue.

**Comment by ayush3160** [comment] 2022-10-16 19:15
Hi @Sarfraz-droid , Please have a look and let me know if any changes are required.

**Comment by ABHISHEK-PANDEY2** [comment] 2022-11-22 11:02
I would like to work on the issue , Could you please assign to me ? @Sarfraz-droid

**Comment by shivareddy6** [comment] 2022-12-09 12:49
@Sarfraz-droid, can i work on this?

**Comment by Phani4658** [comment] 2022-12-20 23:47
Hii @Sarfraz-droid  if the issue is still open i would be glad to work on it

**Comment by shivareddy6** [comment] 2022-12-21 08:21
@Phani4658, actually I'm done working on it, just reviewing the changes

**Closed** 2022-12-23 18:43 UTC
Labels: enhancement, good first issue
