### ISSUE TITLE
make forgot password page responsive

### ISSUE THREAD

**Issue by kushalShukla-web** [scorelab/Codelabz#465] opened 2022-10-08 05:55 UTC
**Describe the bug**
forgot page is not responsive and need some styling . like alignment of buttons on different devices.

**To Reproduce**
1. Go to 'forgot page '
2. Click on 'adjust your screen size on different devices like tablet ..'
3. See error
 **Expected behavior**
there should be a responsiveness and button should be aligned as per different size of view port.

**Screenshots**
screenshot is here
![ezgif-4-db11378e1c](https://user-images.githubusercontent.com/85934954/194691713-8a84eb07-cc07-4ff5-809c-cf7d2b1768a6.gif)

 your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sulogna2001** [comment] 2022-10-11 11:05
hey @kushalShukla-web can I work on this issue

**Comment by ABHISHEK-PANDEY2** [comment] 2022-11-22 13:51
Is the issue still open ? i could work on this

**Comment by Priyansh-Patil** [comment] 2022-12-12 15:08
Hey @kushalShukla-web is this issue open ?

**Comment by infuman69** [comment] 2022-12-12 15:44
@Sarfraz-droid  Can I work on this ?

**Comment by Priyansh-Patil** [comment] 2022-12-12 15:56
@Sarfraz-droid would you assign me this issue,
I can work on this.

**Comment by Phani4658** [comment] 2022-12-20 23:46
@Sarfraz-droid  If the issue is still open please assign it to me I can work on it

**Comment by Shruti0316** [comment] 2022-12-22 10:08
@Sarfraz-droid is the issue still open? Can you assign it to me

**Comment by AjayGurjar1** [comment] 2023-01-12 07:07
i want to work on this issues please assign me this issue

**Comment by ujala19prakash** [comment] 2023-01-15 19:08
I want to work on this issue can you please assign me this issue.

**Comment by kushalShukla-web** [comment] 2023-01-15 19:21
@sulogna2001   yeah you can work on this issue , btw your smile kills me .

**Comment by kushalShukla-web** [comment] 2023-01-15 19:24
@sulogna2001 can you share your insta id here .

**Comment by kushalShukla-web** [comment] 2023-01-15 20:20
> > @sulogna2001 yeah you can work on this issue , btw your smile kills me .
> 
> Then die.

i dont wanna die alone ..

**Comment by kushalShukla-web** [comment] 2023-01-15 20:28
> > @sulogna2001 can you share your insta id here .
> 
> I'll share these nuts on your chin kushal

what did you just type . LOL 😂 😂

**Comment by Rao-Ashu** [comment] 2023-01-17 07:44
Is this issue still open? can you please assign me this issue.

**Comment by deveshshukla** [comment] 2023-01-24 19:03
@Sarfraz-droid @kushalShukla-web  Hey hi. Is this issue open right now, I wanted to work on it, would you assign me.
Things i like to work on it. 1. The responsiveness on mobile/Tab based view 2. Some standard design if required.

**Comment by Novice-expert** [comment] 2023-01-28 06:41
can I work on this issue, I'm really interested?

**Comment by kushalShukla-web** [comment] 2023-01-28 08:17
Ya go ahead

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Novice-expert** [comment] 2023-01-29 16:48
Thank You for your response, but please assign this to me.
Someone else is assigned right now.

**Comment by hirentimbadiya** [comment] 2023-02-07 04:43
is this issue still open , if it is then i can fix it , please assign me this issue.

**Comment by SakshiMahure** [comment] 2023-02-22 17:46
I want to solve this issue, please assign me this issue.

**Comment by ShivanshKhankriyal** [comment] 2023-02-24 16:22
If the issue is still open I would like to be assigned to it and work as a contributor to your organization.

**Comment by tusharmangal** [comment] 2023-03-02 05:58
I want to work on this issue can you please assign me this issue.

**Comment by faraz16iqbal** [comment] 2023-03-12 08:34
@Sarfraz-droid I'd like to work on this since this has been stale for a while.

**Comment by kushalShukla-web** [comment] 2023-03-19 07:45
guys i already created pull request regarding this issue

**Comment by Vidip-Ghosh** [comment] 2023-03-27 13:06
Hey @Sarfraz-droid Can I work on this issue?

**Comment by sud62** [comment] 2023-05-01 08:21
@kushalShukla-web @Sarfraz-droid Is this issue still open? I would love to contribute to this.

**Comment by sud62** [comment] 2023-05-01 08:22
@Shruti0316 can I be the assignee?

**Comment by deep0133** [comment] 2023-05-10 16:07
Is this issue still open?

**Comment by kushalShukla-web** [comment] 2023-05-10 19:17
@deep0133 go for it

**Comment by kushalShukla-web** [comment] 2023-05-10 19:18
@deep0133 go for it

**Comment by Sarfraz-droid** [comment] 2023-05-11 11:20
@deep0133 Thanks for the review. Closing the issue for the same.

**Closed by Sarfraz-droid** 2023-05-11 11:20 UTC
Labels: bug, good first issue
