### ISSUE TITLE
Bug : One User can do multiple likes to post/tutorial

### ISSUE THREAD

**Issue by rohitPandey469** [scorelab/Codelabz#906] opened 2023-10-18 11:54 UTC
**Describe the bug**
Same user can do more than 1 likes to the post/tutorial 

**To Reproduce**
1. Go to http://localhost:5173
2. Click on share tutorial or new codelabz btn and create a new tutorial
3. Click on the vote button of newly created tutorial
4. See Error, same user can do multiple vote until refresh

**Expected behavior**
After clicking it once, the button needs to be disabled and not allow further votes by the same user.

**Screenshots**
![image](https://github.com/scorelab/Codelabz/assets/123815256/b89cf359-fec8-46d2-b649-f36cb953493a)

**Desktop (please complete the following information):**
 - OS : Windows
 - Browser : Chrome
 - Version : latest

**Smartphone (please complete the following information):**
- Not applicable

**Additional context**
-After clicking it once although the appearance of button changed to a disabled one but a user can still click on it.
-**The data in db is not updating, i.e. once upvoted - stays upvoted**

**Comment by perminder-17** [comment] 2023-10-18 12:33
Yes... This is the issue. I can work on this. The liked user must have the data on db too. Can I work on this @ABHISHEK-PANDEY2 @Sarfraz-droid @shivareddy6. Please assign me...

**Comment by Doraemon012** [comment] 2023-10-18 12:35
@ABHISHEK-PANDEY2 I can solve this issue, please assign it to me, I will check the user has liked the post or not, and it it has, no need to increase the likes.

**Comment by rohitPandey469** [comment] 2023-10-18 13:03
@ABHISHEK-PANDEY2 Sir, May I work on this issue please??

**Comment by perminder-17** [comment] 2023-10-18 13:21
I guess issue #887 is the same issue. I guess this is the duplicate of that @rohitPandey469

**Comment by rohitPandey469** [comment] 2023-10-18 13:33
Ahhh... I was trying to raise a issue for "multiple likes" and while creating I headed to not having a proper vote feature, and it's already presented

**Comment by rohitPandey469** [comment] 2023-10-18 13:33
I will close this issue then.

**Closed** 2023-10-18 13:34 UTC
Labels: bug, Feature, UI/UX
