### ISSUE TITLE
back-to-top

### ISSUE THREAD

**Issue by Sumit-pd** [scorelab/Codelabz#649] opened 2023-01-16 11:21 UTC
while scrolling through when the user scrolls to far he/she uses a lot of time to come back to the top.

I wanted to add an back-to-top button so that the user can go back to the top of the page using this button

**Additional context**
![download](https://user-images.githubusercontent.com/88550925/212666403-29906649-1412-4d5e-a1eb-3d7b82412993.png)

this button will be something like this

**Comment by Sumit-pd** [comment] 2023-01-16 11:22
I would like to work on this issue! Someone, please assign it me.

**Comment by parteekcoder** [comment] 2023-01-27 09:36
@Maahi10001 could you please assign me this issue

**Comment by Shashank2104125** [comment] 2023-01-29 10:25
@Maahi10001, @Sarfraz-droid Sir, could you please assign me this issue

**Comment by nsundriyal62** [comment] 2023-01-30 05:56
current,y i am  working on this issue in other organisation repo. could you please assign it to me

**Comment by phanendharreddy** [comment] 2023-03-15 19:29
I'm on it.

**Comment by Vivekkushwaha123** [comment] 2023-03-18 18:00
@Maahi10001  https://github.com/scorelab/Codelabz/pull/762 I added this feature plz check this

**Comment by phanendharreddy** [comment] 2023-03-18 18:53
Yeah, I've seen it 
But merging is undone, right?
And the issue is currently staled and I picked it up.

**Closed** 2023-03-19 05:48 UTC
